services:
  - type: web
    name: python-face-rec
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:5000 --workers 3"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false
    plan: free
    disk:
      sizeGB: 1
    healthCheckPath: "/"
